package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/spf13/afero"
)

func main() {
	var output string
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), `Usage: %s [flags] <dir>

Arguments:
  dir     search for .opt files in dir

`, os.Args[0])
		flag.PrintDefaults()
	}
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		log.Fatalf("expected 1 argument, got %v", args)
	}
	dir := args[0]

	fs := afero.NewBasePathFs(afero.NewOsFs(), dir)
	files, err := afero.Glob(fs, "**/*.opt")
	if err != nil {
		log.Fatalf("failed to glob files in %s: %v", dir, err)
	}

	contents := make([]string, 0, len(files))
	var errs error
	for _, file := range files {
		content, err := afero.ReadFile(fs, file)
		if err != nil {
			errs = errors.Join(errs, fmt.Errorf("failed to read file %s: %w", file, err))
			continue
		}
		contents = append(contents, string(content))
	}
	if errs != nil {
		log.Fatalf("failed to read files in %s: %v", dir, errs)
	}

	records := make([]optRecord, 0, len(contents))
	for _, content := range contents {
		records = append(records, parseOptRecords(content)...)
	}

	records = mergeOptRecords(records)

	config := translateOptRecords(records)

	w := os.Stdout
	if output != "" {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			log.Fatalf("failed to create output directory: %v", err)
		}

		f, err := os.Create(output)
		if err != nil {
			log.Fatalf("failed to create output file: %v", err)
		}
		defer f.Close()
		w = f
	}

	if _, err := fmt.Fprintf(w, `// Code generated by cdbconfiggen. DO NOT EDIT.

package gcc

import "github.com/EthanKim8683/cpx/internal/cdb"

var CDBConfig = %#v
`, config); err != nil {
		log.Fatalf("failed to write config: %v", err)
	}
}
