// Package main implements a code generator that parses GCC's .opt option files
// and translates them into an optimized static *cdb.Config for the cpx shim.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/EthanKim8683/cpx/internal/cdb"
	"github.com/spf13/afero"
)

func main() {
	var output string
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, `Usage: %s [flags] <dir>

Arguments:
  dir     search for .opt files in dir

`, os.Args[0])
		flag.PrintDefaults()
	}
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		flag.Usage()
		os.Exit(1)
	}
	dir := args[0]

	fs := afero.NewBasePathFs(afero.NewOsFs(), dir)
	files, err := afero.Glob(fs, "**/*.opt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to glob files in %s: %v\n", dir, err)
		os.Exit(1)
	}

	contents := make([]string, 0, len(files))
	var errs error
	for _, file := range files {
		content, err := afero.ReadFile(fs, file)
		if err != nil {
			errs = errors.Join(errs, fmt.Errorf("failed to read file %s: %w", file, err))
			continue
		}
		contents = append(contents, string(content))
	}
	if errs != nil {
		fmt.Fprintf(os.Stderr, "failed to read files in %s: %v\n", dir, errs)
		os.Exit(1)
	}

	records := make([]optRecord, 0, len(contents))
	for _, content := range contents {
		records = append(records, parseOptRecords(content)...)
	}

	records = mergeOptRecords(records)

	config := translateOptRecords(records)

	var buf bytes.Buffer
	if _, err := fmt.Fprintf(&buf, `// Code generated by cdbconfiggen. DO NOT EDIT.

package gcc

import "github.com/EthanKim8683/cpx/internal/cdb"

var CDBConfig = %#v
`, cdb.NewConfig(config)); err != nil {
		fmt.Fprintf(os.Stderr, "failed to format config: %v\n", err)
		os.Exit(1)
	}

	if output == "" {
		if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write config to stdout: %v\n", err)
			os.Exit(1)
		}
	} else {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "failed to create output directory: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(output, buf.Bytes(), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write output file: %v\n", err)
			os.Exit(1)
		}
	}
}
