version: 3
dotenv: ['.env']
includes:
  gcc: ./internal/gcc/Taskfile.yml
  clang: ./internal/clang/Taskfile.yml
tasks:
# TODO: add tasks for building shims; remember gxx -> g++, clangxx -> clang++
# must depend on generated cdb configs
  bootstrap:
    desc: Bootstrap GCC and Clang integration
    cmds:
      - task: gcc:bootstrap
      - task: clang:bootstrap