//go:build ignore

package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/EthanKim8683/cpx/internal/config"
)

func writeGCCInfo(ctx context.Context, w io.Writer, gcc string) error {
	output, err := exec.CommandContext(ctx, gcc, "--version").Output()
	if err != nil {
		return err
	}

	version, _, _ := strings.Cut(string(output), "\n")
	fmt.Fprintf(w, "// executable: %s\n", gcc)
	fmt.Fprintf(w, "// version:    %s\n", strings.TrimSpace(version))
	return nil
}

func writeDefines(ctx context.Context, w io.Writer, gcc string, language string) error {
	output, err := exec.CommandContext(ctx, gcc, "-E", "-dM", "-x", language, os.DevNull).Output()
	if err != nil {
		return err
	}

	for line := range strings.SplitSeq(strings.TrimSpace(string(output)), "\n") {
		tokens := strings.SplitN(strings.TrimSpace(line), " ", 3)
		switch len(tokens) {
		case 2:
			fmt.Fprintf(w, "\t%s,\n", strconv.Quote(fmt.Sprintf("-D%s", tokens[1])))
		case 3:
			fmt.Fprintf(w, "\t%s,\n", strconv.Quote(fmt.Sprintf("-D%s=%s", tokens[1], tokens[2])))
		}
	}
	return nil
}

func writeIncludes(ctx context.Context, w io.Writer, gcc string, language string) error {
	output, err := exec.CommandContext(ctx, gcc, "-E", "-v", "-x", language, os.DevNull).CombinedOutput()
	if err != nil {
		return err
	}

	write := false
	for line := range strings.SplitSeq(strings.TrimSpace(string(output)), "\n") {
		line = strings.TrimSpace(line)
		switch {
		case line == "#include <...> search starts here:":
			write = true
		case line == "End of search list.":
			write = false
		case write:
			fmt.Fprintf(w, "\t%s,\n", strconv.Quote(fmt.Sprintf("-isystem%s", line)))
		}
	}
	return nil
}

func main() {
	cfg := config.Load()
	ctx := context.Background()

	gcc := cfg.Gpp
	if gcc == "" {
		gcc = "g++"
	}
	gcc, err := exec.LookPath(gcc)
	if err != nil {
		log.Fatalf("resolving gcc: %v", err)
	}

	var b bytes.Buffer
	var errs error

	b.WriteString(`// Code generated by flaggen.go. DO NOT EDIT.
//
`)
	errs = errors.Join(errs, writeGCCInfo(ctx, &b, gcc))
	b.WriteString(`
package gcc

var gccCFlags = []string{
	"-xc",
	"-undef",
`)
	errs = errors.Join(errs, writeDefines(ctx, &b, gcc, "c"))
	errs = errors.Join(errs, writeIncludes(ctx, &b, gcc, "c"))
	b.WriteString(`}

var gccCPPFlags = []string{
	"-xc++",
	"-undef",
`)
	errs = errors.Join(errs, writeDefines(ctx, &b, gcc, "c++"))
	errs = errors.Join(errs, writeIncludes(ctx, &b, gcc, "c++"))
	b.WriteString("}")
	if errs != nil {
		log.Fatal(errs.Error())
	}

	if err := os.WriteFile("generated_flags.go", b.Bytes(), 0644); err != nil {
		log.Fatalf("writing generated_flags.go: %v", err)
	}
}
