{
	echo "// Code generated by generate_flags.sh. DO NOT EDIT."
	echo
	echo "package gcc"
	echo
	echo "var clangFlags = []string{"
	{
		g++ -v -E -x c - /dev/null
		g++ -v -E -x c++ - /dev/null
	} 2>&1 \
		| grep -E '^[[:space:]][^[:space:]]+$' \
		| sort -u \
		| while read -r path; do
			echo '  "-isystem'$path'",'
		done
	echo "}"
} > "generated_flags.go"