#!/usr/bin/env sh
set -eu

# TODO: Programmatically determine whether to use C or C++ flags
{
	echo "// Code generated by generate_flags.sh. DO NOT EDIT."
	echo
	echo "package gcc"
	echo
	echo "var clangFlags = []string{"
	echo "  \"-undef\","
	g++ -E -dM -x c++ /dev/null \
		| awk '{
			name = $2
			$1 = $2 = ""
			sub(/^ +/, "")
			gsub(/\\/, "\\\\")
			gsub(/"/, "\\\"")
			printf "  \"-D%s=%s\",\n", name, $0
		}'
	g++ -v -E -x c++ /dev/null 2>&1 \
		| grep -E '^[[:space:]][^[:space:]]+$' \
		| awk '{
			sub(/^ +/, "")
			printf "  \"-isystem%s\",\n", $0
		}'
	echo "}"
} > "generated_flags.go"