// cdbconfiggen generates Clang CDB option configurations from TableGen JSON
// dumps. It reads a JSON dump produced by clang-tblgen or llvm-tblgen and
// writes a Go source file containing a *cdb.Config.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/EthanKim8683/cpx/internal/cdb"
)

func main() {
	var output string
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, `Usage: %s [flags] <dump>

Arguments:
  dump    path to TableGen JSON dump

`, os.Args[0])
		flag.PrintDefaults()
	}
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		log.Fatalf("expected 1 argument, got %v", args)
	}
	dumpFile := args[0]

	data, err := os.ReadFile(dumpFile)
	if err != nil {
		log.Fatalf("failed to read dump file: %v", err)
	}

	dump, err := unmarshalDump(data)
	if err != nil {
		log.Fatalf("failed to unmarshal dump: %v", err)
	}

	patterns, err := translateDump(dump)
	if err != nil {
		log.Fatalf("failed to translate dump: %v", err)
	}

	w := os.Stdout
	if output != "" {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			log.Fatalf("failed to create output directory: %v", err)
		}

		f, err := os.Create(output)
		if err != nil {
			log.Fatalf("failed to create output file: %v", err)
		}
		defer f.Close()
		w = f
	}

	if _, err := fmt.Fprintf(w, `// Code generated by cdbconfiggen. DO NOT EDIT.

package clang

import "github.com/EthanKim8683/cpx/internal/cdb"

var CDBConfig = %#v
`, cdb.NewConfig(patterns)); err != nil {
		log.Fatalf("failed to write config: %v", err)
	}
}
