// Package main generates Clang CDB option configurations from TableGen JSON
// dumps. It reads a JSON dump produced by clang-tblgen or llvm-tblgen and
// writes a Go source file containing a *cdb.Config.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/EthanKim8683/cpx/internal/cdb"
)

func main() {
	var output string
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, `Usage: %s [flags] <dump>

Arguments:
  dump    path to TableGen JSON dump

`, os.Args[0])
		flag.PrintDefaults()
	}
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		flag.Usage()
		os.Exit(1)
	}
	dumpFile := args[0]

	data, err := os.ReadFile(dumpFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read dump file: %v\n", err)
		os.Exit(1)
	}

	dump, err := unmarshalDump(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to unmarshal dump: %v\n", err)
		os.Exit(1)
	}

	patterns, err := translateDump(dump)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to translate dump: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	if _, err := fmt.Fprintf(&buf, `// Code generated by cdbconfiggen. DO NOT EDIT.

package clang

import "github.com/EthanKim8683/cpx/internal/cdb"

var CDBConfig = %#v
`, cdb.NewConfig(patterns)); err != nil {
		fmt.Fprintf(os.Stderr, "failed to format config: %v\n", err)
		os.Exit(1)
	}

	if output == "" {
		if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write config to stdout: %v\n", err)
			os.Exit(1)
		}
	} else {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "failed to create output directory: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(output, buf.Bytes(), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write output file: %v\n", err)
			os.Exit(1)
		}
	}
}
