//go:build ignore

package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/EthanKim8683/cpx/internal/config"
	"github.com/joho/godotenv"
)

var includeRegexp = regexp.MustCompile(`(?m)^\s(\S+)$`)

func writeDefines(ctx context.Context, executable string, w io.Writer) error {
	output, err := exec.CommandContext(ctx, executable, "-E", "-dM", "-x", "c++", os.DevNull).Output()
	if err != nil {
		return err
	}

	lines := strings.Split(string(output), "\n")
	for _, line := range lines {
		tokens := strings.SplitN(line, " ", 3)
		if len(tokens) < 3 {
			continue
		}
		var (
			identifier = tokens[1]
			value      = tokens[2]
		)
		value = strings.ReplaceAll(value, `\`, `\\`)
		value = strings.ReplaceAll(value, `"`, `\"`)
		fmt.Fprintf(w, "\t\"-D%s=%s\",\n", identifier, value)
	}
	return nil
}

func writeIncludes(ctx context.Context, executable string, w io.Writer) error {
	output, err := exec.CommandContext(ctx, executable, "-v", "-E", "-x", "c++", os.DevNull).CombinedOutput()
	if err != nil {
		return err
	}

	matches := includeRegexp.FindAllStringSubmatch(string(output), -1)
	for _, match := range matches {
		fmt.Fprintf(w, "\t\"-isystem%s\",\n", match[1])
	}
	return nil
}

func main() {
	godotenv.Load("../../../.env")
	cfg := config.Load()
	ctx := context.Background()

	var b bytes.Buffer
	b.WriteString(`// Code generated by flaggen.go. DO NOT EDIT.

package gpp

var flags = []string{
	"-undef",
`)

	var errs error
	if err := writeDefines(ctx, cfg.Gpp, &b); err != nil {
		errs = errors.Join(errs, fmt.Errorf("writing defines: %w", err))
	}
	if err := writeIncludes(ctx, cfg.Gpp, &b); err != nil {
		errs = errors.Join(errs, fmt.Errorf("writing includes: %w", err))
	}
	if errs != nil {
		log.Fatal(errs.Error())
	}

	b.WriteString("}")
	os.WriteFile("generated_flags.go", b.Bytes(), 0644)
}
