//go:build ignore

package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/EthanKim8683/cpx/internal/config"
)

var includeRegexp = regexp.MustCompile(`(?m)^\s(\S+)$`)

func writeGppInfo(ctx context.Context, w io.Writer, gpp string) error {
	output, err := exec.CommandContext(ctx, gpp, "--version").Output()
	if err != nil {
		return err
	}

	version, _, _ := strings.Cut(string(output), "\n")
	fmt.Fprintf(w, "// executable: %s\n", gpp)
	fmt.Fprintf(w, "// version:    %s\n", strings.TrimSpace(version))
	return nil
}

func writeDefines(ctx context.Context, gpp string, w io.Writer) error {
	output, err := exec.CommandContext(ctx, gpp, "-E", "-dM", "-x", "c++", os.DevNull).Output()
	if err != nil {
		return err
	}

	for line := range strings.SplitSeq(strings.TrimSpace(string(output)), "\n") {
		tokens := strings.SplitN(line, " ", 3)
		if tokens[0] != "#define" {
			continue
		}
		switch len(tokens) {
		case 2:
			fmt.Fprintf(w, "\t\"-D%s\",\n", tokens[1])
		case 3:
			definition := tokens[2]
			definition = strings.ReplaceAll(definition, `\`, `\\`)
			definition = strings.ReplaceAll(definition, `"`, `\"`)
			fmt.Fprintf(w, "\t\"-D%s=%s\",\n", tokens[1], definition)
		}
	}
	return nil
}

func writeIncludes(ctx context.Context, gpp string, w io.Writer) error {
	output, err := exec.CommandContext(ctx, gpp, "-v", "-E", "-x", "c++", os.DevNull).CombinedOutput()
	if err != nil {
		return err
	}

	matches := includeRegexp.FindAllStringSubmatch(string(output), -1)
	for _, match := range matches {
		fmt.Fprintf(w, "\t\"-isystem%s\",\n", match[1])
	}
	return nil
}

func main() {
	cfg := config.Load()
	ctx := context.Background()

	gpp := cfg.Gpp
	if gpp == "" {
		gpp = "g++"
	}
	gpp, err := exec.LookPath(gpp)
	if err != nil {
		log.Fatalf("resolving g++: %v", err)
	}

	var b bytes.Buffer
	var errs error

	b.WriteString(`// Code generated by flaggen.go. DO NOT EDIT.
//
`)
	if err := writeGppInfo(ctx, &b, gpp); err != nil {
		errs = errors.Join(errs, fmt.Errorf("writing g++ info: %w", err))
	}
	b.WriteString(`
package gpp

var flags = []string{
	"-undef",
`)
	if err := writeDefines(ctx, gpp, &b); err != nil {
		errs = errors.Join(errs, fmt.Errorf("writing defines: %w", err))
	}
	if err := writeIncludes(ctx, gpp, &b); err != nil {
		errs = errors.Join(errs, fmt.Errorf("writing includes: %w", err))
	}
	b.WriteString("}")
	if errs != nil {
		log.Fatal(errs.Error())
	}

	if err := os.WriteFile("generated_flags.go", b.Bytes(), 0644); err != nil {
		log.Fatalf("writing generated_flags.go: %v", err)
	}
}
