// Package main implements the Clang option configuration generator tool.
// For the general game plan of option configuration and static lookup, refer to:
// internal/cdb/config.go
//
// This file is the entrypoint to coordinate fetching option files, compiling them using clang-tblgen, and writing the final configuration.
package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"

	"github.com/EthanKim8683/cpx/internal/config"
	"github.com/spf13/afero"
)

func main() {
	var output string
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	tmpDir, err := os.MkdirTemp("", "clangconfiggen-*")
	if err != nil {
		log.Fatalf("failed to create temporary directory: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	tmpFS := afero.NewBasePathFs(afero.NewOsFs(), tmpDir)

	// Fetch Options.td (trying driver folder, then new options folder)
	var c http.Client
	var errs error
	errs = errors.Join(errs, fetchFile(&c, tmpFS, cfg.LLVMBaseURL, "clang/include/clang/Options/Options.td"))
	errs = errors.Join(errs, fetchFile(&c, tmpFS, cfg.LLVMBaseURL, "clang/include/clang/Options/FlangOptions.td"))
	errs = errors.Join(errs, fetchFile(&c, tmpFS, cfg.LLVMBaseURL, "llvm/include/llvm/Option/OptParser.td"))
	if errs != nil {
		log.Fatalf("failed to stage files: %v", errs)
	}

	dump, err := dumpJSON(cfg.ClangTblgen, tmpDir)
	if err != nil {
		log.Fatalf("failed to dump JSON: %v", err)
	}

	parsedDump, err := parseDump(dump)
	if err != nil {
		log.Fatalf("failed to parse dump: %v", err)
	}

	config := buildConfig(parsedDump)

	w := os.Stdout
	if output != "" {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			log.Fatalf("failed to create output directory: %v", err)
		}

		f, err := os.Create(output)
		if err != nil {
			log.Fatalf("failed to create output file: %v", err)
		}
		defer f.Close()
		w = f
	}

	if _, err := fmt.Fprintf(w, `// Code generated by clangconfiggen. DO NOT EDIT.
package config

import "github.com/EthanKim8683/cpx/internal/cdb"

var Clang = %#v
`, &config); err != nil {
		log.Fatalf("failed to write config: %v", err)
	}
}
