package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	var output string
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), `Usage: %s [flags] <dump>
  dump
	path to TableGen JSON dump
`, os.Args[0])
		flag.PrintDefaults()
	}
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		log.Fatalf("expected 1 argument, got %v", args)
	}
	dumpFile := args[0]

	data, err := os.ReadFile(dumpFile)
	if err != nil {
		log.Fatalf("failed to read dump file: %v", err)
	}

	dump, err := unmarshalDump(data)
	if err != nil {
		log.Fatalf("failed to parse dump: %v", err)
	}

	cfg, err := buildConfig(dump)
	if err != nil {
		log.Fatalf("failed to build config: %v", err)
	}

	w := os.Stdout
	if output != "" {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			log.Fatalf("failed to create output directory: %v", err)
		}

		f, err := os.Create(output)
		if err != nil {
			log.Fatalf("failed to create output file: %v", err)
		}
		defer f.Close()
		w = f
	}

	if _, err := fmt.Fprintf(w, `// Code generated by clangconfiggen. DO NOT EDIT.
package config

import "github.com/EthanKim8683/cpx/internal/cdb"

var Clang = %#v
`, cfg); err != nil {
		log.Fatalf("failed to write config: %v", err)
	}
}
