package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	var output string
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), `Usage: %s [flags] <dir>
  dir
	search for .opt files in dir
`, os.Args[0])
		flag.PrintDefaults()
	}
	flag.StringVar(&output, "o", "", "write output to `file`")
	flag.Parse()

	args := flag.Args()
	if len(args) != 1 {
		log.Fatalf("expected 1 argument, got %v", args)
	}
	dir := args[0]

	contents, err := readOptFiles(dir)
	if err != nil {
		log.Fatalf("failed to read opt files: %v", err)
	}

	records := make([]optRecord, 0, len(contents))
	for _, content := range contents {
		records = append(records, extractOptRecords(content)...)
	}

	records = mergeRecords(records)

	config := buildConfig(records)

	w := os.Stdout
	if output != "" {
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			log.Fatalf("failed to create output directory: %v", err)
		}

		f, err := os.Create(output)
		if err != nil {
			log.Fatalf("failed to create output file: %v", err)
		}
		defer f.Close()
		w = f
	}

	if _, err := fmt.Fprintf(w, `// Code generated by gccconfiggen. DO NOT EDIT.
package config

import "github.com/EthanKim8683/cpx/internal/cdb"

var GCC = %#v
`, config); err != nil {
		log.Fatalf("failed to write config: %v", err)
	}
}
